version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
    container_name: app_container
    ports:
      - "3000:5000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: your_username
      DB_PASSWORD: your_password
      DB_DATABASE: your_database
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
